import type { ModelInfo } from "../model.js"

export type VscodeLlmModelId = keyof typeof vscodeLlmModels

export const vscodeLlmDefaultModelId: VscodeLlmModelId = "claude-sonnet-4.5"

// contextWindow = advertised window; maxInputTokens = measured single-message accepted ceiling, and
// it is what the condense gate and the context gauge enforce — so the two deliberately diverge where
// advertised exceeds measured. Values MUST be re-measured, never hand-tuned or borrowed from a
// sibling row. Per-row evidence, lower-bound and vendor caveats:
// myplans/vscode-lm-model-table-integrity/vscode-lm-model-table-integrity-design.md
export const vscodeLlmModels = {
	// Measured 2026-09-23, VS Code 1.137.0/copilot, 13 trials: accepted 677108, rejected 695778.
	// Refusals prevent an exact ceiling; keep the accepted lower bound rather than a sibling limit.
	// Image/tool inputs succeeded; caching `false` is an unverified schema-required default.
	"claude-opus-5.5": {
		contextWindow: 871793,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "claude-opus-5.5",
		version: "claude-opus-5.5",
		name: "Claude Opus 5.5",
		supportsToolCalling: true,
		maxInputTokens: 677108,
	},
	"claude-opus-5": {
		contextWindow: 935793,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "claude-opus-5",
		version: "claude-opus-5",
		name: "Claude Opus 5",
		supportsToolCalling: true,
		maxInputTokens: 680456,
	},
	"claude-opus-4.8": {
		contextWindow: 679560,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "claude-opus-4.8",
		version: "claude-opus-4.8",
		name: "Claude Opus 4.8",
		supportsToolCalling: true,
		maxInputTokens: 197897,
	},
	"claude-opus-4.7": {
		contextWindow: 197897,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "claude-opus-4.7",
		version: "claude-opus-4.7",
		name: "Claude Opus 4.7",
		supportsToolCalling: true,
		maxInputTokens: 197897,
	},
	"claude-opus-4.6": {
		contextWindow: 197897,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "claude-opus-4.6",
		version: "claude-opus-4.6",
		name: "Claude Opus 4.6",
		supportsToolCalling: true,
		maxInputTokens: 197897,
	},
	"claude-opus-4.5": {
		contextWindow: 167790,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "claude-opus-4.5",
		version: "claude-opus-4.5",
		name: "Claude Opus 4.5",
		supportsToolCalling: true,
		maxInputTokens: 167790,
	},
	"claude-sonnet-5": {
		contextWindow: 925449,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "claude-sonnet-5",
		version: "claude-sonnet-5",
		name: "Claude Sonnet 5",
		supportsToolCalling: true,
		maxInputTokens: 925449,
	},
	"claude-sonnet-4.6": {
		contextWindow: 197896,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "claude-sonnet-4.6",
		version: "claude-sonnet-4.6",
		name: "Claude Sonnet 4.6",
		supportsToolCalling: true,
		maxInputTokens: 197896,
	},
	"claude-sonnet-4.5": {
		contextWindow: 167790,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "claude-sonnet-4.5",
		version: "claude-sonnet-4.5",
		name: "Claude Sonnet 4.5",
		supportsToolCalling: true,
		maxInputTokens: 167790,
	},
	"claude-haiku-4.5": {
		contextWindow: 135790,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "claude-haiku-4.5",
		version: "claude-haiku-4.5",
		name: "Claude Haiku 4.5",
		supportsToolCalling: true,
		maxInputTokens: 135790,
	},
	// Measured 2026-09-23, VS Code 1.137.0/copilot, 20-trial binary search: 271789 accepted, 271790 rejected.
	// Image/tool inputs succeeded; caching `false` is an unverified schema-required default.
	"gpt-6-astra": {
		contextWindow: 921793,
		supportsImages: true,
		supportsPromptCache: false,
		family: "gpt-6-astra",
		version: "gpt-6-astra",
		name: "GPT-6 Astra",
		supportsToolCalling: true,
		maxInputTokens: 271789,
	},
	"gpt-5.6-luna": {
		contextWindow: 199753,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gpt-5.6-luna",
		version: "gpt-5.6-luna",
		name: "GPT-5.6 Luna",
		supportsToolCalling: true,
		maxInputTokens: 199753,
	},
	"gpt-5.6-sol": {
		contextWindow: 271785,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gpt-5.6-sol",
		version: "gpt-5.6-sol",
		name: "GPT-5.6 Sol",
		supportsToolCalling: true,
		maxInputTokens: 271785,
	},
	"gpt-5.6-terra": {
		contextWindow: 271785,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gpt-5.6-terra",
		version: "gpt-5.6-terra",
		name: "GPT-5.6 Terra",
		supportsToolCalling: true,
		maxInputTokens: 271785,
	},
	"gpt-5.5": {
		contextWindow: 268426,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gpt-5.5",
		version: "gpt-5.5",
		name: "GPT-5.5",
		supportsToolCalling: true,
		maxInputTokens: 268426,
	},
	"gpt-5.4": {
		contextWindow: 268424,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gpt-5.4",
		version: "gpt-5.4",
		name: "GPT-5.4",
		supportsToolCalling: true,
		maxInputTokens: 268424,
	},
	"gpt-5.4-mini": {
		contextWindow: 271790,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gpt-5.4-mini",
		version: "gpt-5.4-mini",
		name: "GPT-5.4 mini",
		supportsToolCalling: true,
		maxInputTokens: 271790,
	},
	"gpt-5.3-codex": {
		contextWindow: 271790,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gpt-5.3-codex",
		version: "gpt-5.3-codex",
		name: "GPT-5.3-Codex",
		supportsToolCalling: true,
		maxInputTokens: 271790,
	},
	"gpt-5-mini": {
		contextWindow: 127790,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gpt-5-mini",
		version: "gpt-5-mini",
		name: "GPT-5 mini",
		supportsToolCalling: true,
		maxInputTokens: 127790,
	},
	"gpt-4o-mini": {
		contextWindow: 12078,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gpt-4o-mini",
		version: "gpt-4o-mini-2024-07-18",
		name: "GPT-4o mini",
		supportsToolCalling: true,
		maxInputTokens: 12078,
	},
	"grok-4.6": {
		contextWindow: 424794,
		// Grok image requests failed with a nondiagnostic HTTP 400, so support is unknown; false is a
		// deliberate disable pending evidence, not a measured absence of capability.
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "grok-4.6",
		version: "grok-4.6",
		name: "Grok 4.6",
		supportsToolCalling: true,
		maxInputTokens: 199784,
	},
	"grok-4.5": {
		contextWindow: 424794,
		// See grok-4.6 above: images disabled pending evidence, not proven unsupported.
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "grok-4.5",
		version: "grok-4.5",
		name: "Grok 4.5",
		supportsToolCalling: true,
		maxInputTokens: 199783,
	},
	"gemini-3.8-flash": {
		contextWindow: 982833,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gemini-3.8-flash",
		version: "gemini-3.8-flash",
		name: "Gemini 3.8 Flash",
		supportsToolCalling: true,
		// Largest accepted trial with no rejection observed: a lower bound, not a measured ceiling.
		maxInputTokens: 955113,
	},
	"gemini-3.7-flash": {
		contextWindow: 935793,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gemini-3.7-flash",
		version: "gemini-3.7-flash",
		name: "Gemini 3.7 Flash",
		supportsToolCalling: true,
		maxInputTokens: 935783,
	},
	"gemini-3.6-flash": {
		contextWindow: 935793,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gemini-3.6-flash",
		version: "gemini-3.6-flash",
		name: "Gemini 3.6 Flash",
		supportsToolCalling: true,
		maxInputTokens: 935785,
	},
	"gemini-3.1-pro-preview": {
		contextWindow: 197897,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gemini-3.1-pro-preview",
		version: "gemini-3.1-pro-preview",
		name: "Gemini 3.1 Pro (Preview)",
		supportsToolCalling: true,
		maxInputTokens: 197897,
	},
	"gemini-3.5-flash": {
		contextWindow: 197895,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gemini-3.5-flash",
		version: "gemini-3.5-flash",
		name: "Gemini 3.5 Flash",
		supportsToolCalling: true,
		maxInputTokens: 197895,
	},
	"gemini-3-flash": {
		contextWindow: 108594,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gemini-3-flash",
		version: "gemini-3-flash-preview",
		name: "Gemini 3 Flash (Preview)",
		supportsToolCalling: true,
		maxInputTokens: 108594,
	},
	"gemini-2.5-pro": {
		contextWindow: 108594,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		family: "gemini-2.5-pro",
		version: "gemini-2.5-pro",
		name: "Gemini 2.5 Pro",
		supportsToolCalling: true,
		maxInputTokens: 108594,
	},
} as const satisfies Record<
	string,
	ModelInfo & {
		family: string
		version: string
		name: string
		supportsToolCalling: boolean
		maxInputTokens: number
	}
>
